[general]
# (optional other general settings)

[connections.supabase]  # falls du st.experimental_connection nutzen willst
# Hier kann man auch Supabase-Daten eintragen, aber wir nutzen unten die direkte Variante.

# Oder direkte secrets:
SUPABASE_URL = "https://<YOUR_PROJECT>.supabase.co"
SUPABASE_KEY = "<your-anon-or-service-key>"
